### PR TITLE
Merge effect-handlers/function-references with upstream/main

### PR DESCRIPTION
**Pull request by dhil**
Failure log after merge:
```
$ cargo test
...
failures:
    wast::Cranelift::misc::function_references::table_get
    wast::Cranelift::misc::function_references::table_get_pooling
    wast::Cranelift::misc::function_references::table_set
    wast::Cranelift::misc::function_references::table_set_pooling
    wast::Cranelift::spec::function_references::br_on_non_null
    wast::Cranelift::spec::function_references::br_on_non_null_pooling
    wast::Cranelift::spec::function_references::br_table
    wast::Cranelift::spec::function_references::br_table_pooling
    wast::Cranelift::spec::function_references::global
    wast::Cranelift::spec::function_references::global_pooling
    wast::Cranelift::spec::function_references::linking
    wast::Cranelift::spec::function_references::linking_pooling
    wast::Cranelift::spec::function_references::local_get
    wast::Cranelift::spec::function_references::local_get_pooling
    wast::Cranelift::spec::function_references::ref_as_non_null
    wast::Cranelift::spec::function_references::ref_as_non_null_pooling
    wast::Cranelift::spec::function_references::return_call_ref
    wast::Cranelift::spec::function_references::return_call_ref_pooling
    wast::Cranelift::spec::function_references::select
    wast::Cranelift::spec::function_references::select_pooling
    wast::Cranelift::spec::function_references::table
    wast::Cranelift::spec::function_references::table_pooling
    wast::Cranelift::spec::function_references::type_equivalence
    wast::Cranelift::spec::function_references::type_equivalence_pooling

test result: FAILED. 856 passed; 24 failed; 10 ignored; 0 measured; 0 filtered out; finished in 79.77s
```

### CODE REVIEW

**Comment by dhil** [comment]
I just merged again. The failure log should be the same:
```
failures:
    wast::Cranelift::misc::function_references::table_get
    wast::Cranelift::misc::function_references::table_get_pooling
    wast::Cranelift::misc::function_references::table_set
    wast::Cranelift::misc::function_references::table_set_pooling
    wast::Cranelift::spec::function_references::br_on_non_null
    wast::Cranelift::spec::function_references::br_on_non_null_pooling
    wast::Cranelift::spec::function_references::br_table
    wast::Cranelift::spec::function_references::br_table_pooling
    wast::Cranelift::spec::function_references::global
    wast::Cranelift::spec::function_references::global_pooling
    wast::Cranelift::spec::function_references::linking
    wast::Cranelift::spec::function_references::linking_pooling
    wast::Cranelift::spec::function_references::local_get
    wast::Cranelift::spec::function_references::local_get_pooling
    wast::Cranelift::spec::function_references::ref_as_non_null
    wast::Cranelift::spec::function_references::ref_as_non_null_pooling
    wast::Cranelift::spec::function_references::return_call_ref
    wast::Cranelift::spec::function_references::return_call_ref_pooling
    wast::Cranelift::spec::function_references::select
    wast::Cranelift::spec::function_references::select_pooling
    wast::Cranelift::spec::function_references::table
    wast::Cranelift::spec::function_references::table_pooling
    wast::Cranelift::spec::function_references::type_equivalence
    wast::Cranelift::spec::function_references::type_equivalence_pooling

test result: FAILED. 856 passed; 24 failed; 10 ignored; 0 measured; 0 filtered out; finished in 80.89s
```

**Comment by dhil** [comment]
@CosineP can I ask you to check that the function-references stuff hasn't regressed, i.e. that you can pass the same tests as before?

**Comment by CosineP** [comment]
Just looking at your list there's definitely regressions; local_[sg]et and table_[gs]et should work for starters.   This looks like the same set as before you had up-to-date modules maybe?   Ill check this out and see if I see any more obvious details though

**Comment by dhil** [comment]
Ah, I just pulled the old failure log from before the merge:
```
failures:
    component_model::dynamic::everything
    component_model::dynamic::flags
    component_model::dynamic::lists
    component_model::dynamic::primitives
    component_model::dynamic::records
    component_model::dynamic::strings
    component_model::dynamic::variants
    component_model::func::bools
    component_model::func::char_bool_memory
    component_model::func::chars
    component_model::func::drop_component_still_works
    component_model::func::errors_that_poison_instance
    component_model::func::expected
    component_model::func::fancy_list
    component_model::func::floats
    component_model::func::integers
    component_model::func::invalid_alignment
    component_model::func::lower_then_lift
    component_model::func::many_parameters
    component_model::func::option
    component_model::func::raw_slice_of_various_types
    component_model::func::run_export_with_internal_adapter
    component_model::func::some_traps
    component_model::func::string_list_oob
    component_model::func::strings
    component_model::func::thunks
    component_model::func::tuple_result
    component_model::func::tuples
    component_model::func::type_layers
    component_model::func::typecheck
    component_model::import::attempt_to_leave_during_malloc
    component_model::import::attempt_to_reenter_during_host
    component_model::import::bad_import_alignment
    component_model::import::can_compile
    component_model::import::no_actual_wasm_code
    component_model::import::simple
    component_model::import::stack_and_heap_args_and_rets
    component_model::macros::enum_derive
    component_model::macros::flags
    component_model::macros::record_derive
    component_model::macros::union_derive
    component_model::macros::variant_derive
    component_model::nested::nested_many_instantiations
    component_model::nested::thread_options_through_inner
    component_model::post_return::invalid_api
    component_model::post_return::invoke_post_return
    component_model::post_return::post_return_all_types
    component_model::post_return::post_return_string
    component_model::post_return::trap_in_post_return_poisons_instance
    wast::Cranelift::spec::function_references::br_table
    wast::Cranelift::spec::function_references::br_table_pooling
    wast::Cranelift::spec::function_references::func_bind
    wast::Cranelift::spec::function_references::func_bind_pooling
    wast::Cranelift::spec::function_references::let_pooling
    wast::Cranelift::spec::function_references::linking
    wast::Cranelift::spec::function_references::linking_pooling
    wast::Cranelift::spec::function_references::r#let
    wast::Cranelift::spec::function_references::return_call_ref
    wast::Cranelift::spec::function_references::return_call_ref_pooling
    wast::Cranelift::spec::function_references::select
    wast::Cranelift::spec::function_references::select_pooling
    wast::Cranelift::spec::function_references::type_equivalence
    wast::Cranelift::spec::function_references::type_equivalence_pooling

test result: FAILED. 732 passed; 63 failed; 10 ignored; 0 measured; 0 filtered out; finished in 12.74s
```
Modulo the components stuff it seems that we have more regressions. I suppose the `br_on_null` and `br_on_non_null` might be failing due to the new encoding using `canonicalise_brif`.

**Comment by dhil** [comment]
I have, seemingly, fixed a couple of tests. The failure log is now:
```
failures:
    wast::Cranelift::spec::function_references::br_on_non_null
    wast::Cranelift::spec::function_references::br_on_non_null_pooling
    wast::Cranelift::spec::function_references::br_table
    wast::Cranelift::spec::function_references::br_table_pooling
    wast::Cranelift::spec::function_references::global
    wast::Cranelift::spec::function_references::global_pooling
    wast::Cranelift::spec::function_references::linking
    wast::Cranelift::spec::function_references::linking_pooling
    wast::Cranelift::spec::function_references::local_get
    wast::Cranelift::spec::function_references::local_get_pooling
    wast::Cranelift::spec::function_references::ref_as_non_null
    wast::Cranelift::spec::function_references::ref_as_non_null_pooling
    wast::Cranelift::spec::function_references::return_call_ref
    wast::Cranelift::spec::function_references::return_call_ref_pooling
    wast::Cranelift::spec::function_references::select
    wast::Cranelift::spec::function_references::select_pooling
    wast::Cranelift::spec::function_references::type_equivalence
    wast::Cranelift::spec::function_references::type_equivalence_pooling

test result: FAILED. 864 passed; 18 failed; 10 ignored; 0 measured; 0 filtered out; finished in 81.17s
```

**Comment by dhil** [comment]
Failure log after last commit:
```
failures:
    wast::Cranelift::spec::function_references::br_on_non_null
    wast::Cranelift::spec::function_references::br_on_non_null_pooling
    wast::Cranelift::spec::function_references::br_table
    wast::Cranelift::spec::function_references::br_table_pooling
    wast::Cranelift::spec::function_references::global
    wast::Cranelift::spec::function_references::global_pooling
    wast::Cranelift::spec::function_references::linking
    wast::Cranelift::spec::function_references::linking_pooling
    wast::Cranelift::spec::function_references::ref_as_non_null
    wast::Cranelift::spec::function_references::ref_as_non_null_pooling
    wast::Cranelift::spec::function_references::return_call_ref
    wast::Cranelift::spec::function_references::return_call_ref_pooling
    wast::Cranelift::spec::function_references::select
    wast::Cranelift::spec::function_references::select_pooling
    wast::Cranelift::spec::function_references::type_equivalence
    wast::Cranelift::spec::function_references::type_equivalence_pooling

test result: FAILED. 866 passed; 16 failed; 10 ignored; 0 measured; 0 filtered out; finished in 76.15s
```

**Comment by dhil** [comment]
Failure log now:
```
failures:
    wast::Cranelift::spec::function_references::br_table
    wast::Cranelift::spec::function_references::br_table_pooling
    wast::Cranelift::spec::function_references::global
    wast::Cranelift::spec::function_references::global_pooling
    wast::Cranelift::spec::function_references::linking
    wast::Cranelift::spec::function_references::linking_pooling
    wast::Cranelift::spec::function_references::ref_as_non_null
    wast::Cranelift::spec::function_references::ref_as_non_null_pooling
    wast::Cranelift::spec::function_references::return_call_ref
    wast::Cranelift::spec::function_references::return_call_ref_pooling
    wast::Cranelift::spec::function_references::select
    wast::Cranelift::spec::function_references::select_pooling
    wast::Cranelift::spec::function_references::type_equivalence
    wast::Cranelift::spec::function_references::type_equivalence_pooling

test result: FAILED. 868 passed; 14 failed; 10 ignored; 0 measured; 0 filtered out; finished in 78.07s
```

**Comment by dhil** [comment]
The following tests seem to fail due to "wrong" error message.
```
wast::Cranelift::spec::function_references::global
wast::Cranelift::spec::function_references::global_pooling
```
The expected error message is embedded in the produced error message. I think we need to ping the wasmtime folks to hear how they want to fix this "failure".

**Comment by dhil** [comment]
Failure log after latest commit:
```
failures:
    wast::Cranelift::spec::function_references::br_table
    wast::Cranelift::spec::function_references::br_table_pooling
    wast::Cranelift::spec::function_references::global
    wast::Cranelift::spec::function_references::global_pooling
    wast::Cranelift::spec::function_references::linking
    wast::Cranelift::spec::function_references::linking_pooling
    wast::Cranelift::spec::function_references::return_call_ref
    wast::Cranelift::spec::function_references::return_call_ref_pooling
    wast::Cranelift::spec::function_references::select
    wast::Cranelift::spec::function_references::select_pooling
    wast::Cranelift::spec::function_references::type_equivalence
    wast::Cranelift::spec::function_references::type_equivalence_pooling

test result: FAILED. 870 passed; 12 failed; 10 ignored; 0 measured; 0 filtered out; finished in 78.40s
```

**Comment by dhil** [comment]
Current status:
```
failures:
    wast::Cranelift::spec::function_references::br_table
    wast::Cranelift::spec::function_references::br_table_pooling
    wast::Cranelift::spec::function_references::linking
    wast::Cranelift::spec::function_references::linking_pooling
    wast::Cranelift::spec::function_references::return_call_ref
    wast::Cranelift::spec::function_references::return_call_ref_pooling
    wast::Cranelift::spec::function_references::select
    wast::Cranelift::spec::function_references::select_pooling
    wast::Cranelift::spec::function_references::type_equivalence
    wast::Cranelift::spec::function_references::type_equivalence_pooling

test result: FAILED. 872 passed; 10 failed; 10 ignored; 0 measured; 0 filtered out; finished in 77.40s
```

**Comment by dhil** [comment]
`br_table` is broken due to a bug in wasm-tools. Here is a minimal failing example:
```wast
(module
  (type $t (func))
  (func $tf)
  (table $t (ref null $t) (elem $tf)))
```

```
wasm-tools$ cargo run -- validate ../wasmtime/test.wast --features function-references
    Finished dev [unoptimized + debuginfo] target(s) in 0.10s
     Running `target/debug/wasm-tools validate ../wasmtime/test.wast --features function-references`
Error: invalid element type `funcref` for table type `(ref null $type)` (at offset 0x1d)
```

**Comment by CosineP** [comment]
That error message is correct!   The shorthand elem syntax always has type funcref, you need to use ref.func explicitly to get the typed version.   My memory is that br_table is one of the correctly failing (outdated) tests due to a syntax error in the test (probably that one!)

**Comment by CosineP** [comment]
i think you're now ahead of where we were in before merge so let's go ahead and merge this in!!!   Thanks for doing all this work!    Sorry ive been in tinygo land

**Comment by dhil** [comment]
I suppose we can briefly chat about this patch when we meet later today.

I fixed the `select` tests. However doing so unveiled that I had implemented a bug which made `table` pass unintended! So, the current status is now:

```
failures:
    wast::Cranelift::spec::function_references::br_table
    wast::Cranelift::spec::function_references::br_table_pooling
    wast::Cranelift::spec::function_references::linking
    wast::Cranelift::spec::function_references::linking_pooling
    wast::Cranelift::spec::function_references::return_call_ref
    wast::Cranelift::spec::function_references::return_call_ref_pooling
    wast::Cranelift::spec::function_references::table
    wast::Cranelift::spec::function_references::table_pooling
    wast::Cranelift::spec::function_references::type_equivalence
    wast::Cranelift::spec::function_references::type_equivalence_pooling

test result: FAILED. 872 passed; 10 failed; 10 ignored; 0 measured; 0 filtered out; finished in 78.49s
```

I think the failures with `table` are due to a bug in table initialisation. I think wasm-tools (wast util) may emit the wrong bytecode. The reason I think this is, that if you compile `table` with the reference interpreter and then run wasmtime on the output, then it returns correctly, i.e.
```
interpreter $ ./wasm ../../wasmtime/tests/spec_testsuite/proposals/function-references/table.wast -o table.wasm
interpreter$ ../../wasmtime/target/debug/wasmtime ./table.wasm --wasm-features function-references
interpreter$ echo $?
0
```
I will have to investigate further. 

I can do a similar thing for the `br_table` test:
```
interpreter$ ./wasm ../../wasmtime/tests/spec_testsuite/proposals/function-references/br_table.wast -o br_table.wasm
interpreter$ ../../wasmtime/target/debug/wasmtime ./br_table.wasm --wasm-features function-references
interpreter$ echo $?
0
```

And `linking`:
```
interpreter$ ./wasm ../../wasmtime/tests/spec_testsuite/proposals/function-references/linking.wast -o linking.wasm
interpreter$ ../../wasmtime/target/debug/wasmtime ./linking.wasm --wasm-features function-references
interpreter$ echo $?
0
```

The tests `type_equivalence` and `return_call_ref` fail regardless (the latter because the instruction hasn't been implemented; I don't know why the former fails yet).

**Comment by CosineP** [comment]
Be careful.   i believe running the reference interpreter on wast, outputting wasm, only outputs the first module of the wast file!   There may be more modules and more tests.  Also, since the tests aren't included in the wasm, you are only checking for a compile without crashes/errors.

**Comment by CosineP** [comment]
i think before we go deeper into this rabbit hole, we should get the tests up to date :)  recall that our wasm-tools changes are tested and passing

**Comment by dhil** [comment]
> Be careful. i believe running the reference interpreter on wast, outputting wasm, only outputs the first module of the wast file! There may be more modules and more tests. Also, since the tests aren't included in the wasm, you are only checking for a compile without crashes/errors.

Interesting. I didn't occur to me as an option.

Nevertheless, I have pushed a few changes for now. I think I understand most of the failures now. I just don't understand how to fix them yet :-)

Current status:
```
failures:
    wast::Cranelift::spec::function_references::br_table
    wast::Cranelift::spec::function_references::br_table_pooling
    wast::Cranelift::spec::function_references::linking
    wast::Cranelift::spec::function_references::linking_pooling
    wast::Cranelift::spec::function_references::return_call_ref
    wast::Cranelift::spec::function_references::return_call_ref_pooling
    wast::Cranelift::spec::function_references::table
    wast::Cranelift::spec::function_references::table_pooling
    wast::Cranelift::spec::function_references::type_equivalence
    wast::Cranelift::spec::function_references::type_equivalence_pooling

test result: FAILED. 872 passed; 10 failed; 10 ignored; 0 measured; 0 filtered out; finished in 77.91s
```

**Pull request merged**
